Bug/dynamic activation url
cboard-org/cboard-api pull request #120
Opened 2021-03-09 21:22 UTC by tomivm

Reading origin header.

2021-03-10 14:17 UTC, martinbedouret requested changes

2021-03-10 14:17 UTC, martinbedouret commented on api/mail/email-verification.js
> +    var d = /DOMAIN/;
use the same pattern as URL, for consistency 
`/\$\{DOMAIN\}/g`

2021-03-10 14:17 UTC, martinbedouret commented on api/mail/index.js
> +      verificationURL: 'DOMAIN/activate/${URL}',
use the same pattern as URL, for consistency 
`${DOMAIN}`

2021-03-10 14:17 UTC, martinbedouret commented on api/mail/index.js
>        resetPasswordURL: 'https://app.cboard.io/reset/${USERID}/${URL}',
we should also implement for this link

2021-03-10 14:17 UTC, martinbedouret commented on api/mail/email-verification.js
>     * @param {object} email - the user's email address
add new parameter in decorators

2021-03-10 15:46 UTC, tomivm commented on api/mail/email-verification.js
>     * @param {object} email - the user's email address
thanks for your feedback!

2021-03-11 11:57 UTC, martinbedouret approved these changes

2021-03-11 12:07 UTC, martinbedouret requested changes

2021-03-11 12:07 UTC, martinbedouret commented on api/mail/email-verification.js
> +    var URL = options.verificationURL.replace(d, domain).replace(r, url);
something is wrong. you replaced the comma by a semicolon!

2021-03-11 19:33 UTC, martinbedouret approved these changes

2021-03-17 16:03 UTC, merged