Feature - Get user location
cboard-org/cboard-api pull request #204
Opened 2022-05-19 20:52 UTC by RodriSanchez1

close #203

2022-07-21 23:02 UTC, tomivm commented on api/controllers/user.js
> +          user.location = {};
i think that is better to set `user.location = null`
for me, it is more clear that the location is not set

2022-07-21 23:18 UTC, tomivm commented on api/controllers/user.js
> +        user.location = {};
The same as the comment before
https://github.com/cboard-org/cboard-api/pull/204/files#r927164259

2022-07-22 02:15 UTC, martinbedouret requested changes

2022-07-22 02:15 UTC, martinbedouret commented on api/controllers/user.js
> +    const newLocation = await getLocation(ip);
try/catch here

2022-07-22 02:15 UTC, martinbedouret commented on api/controllers/user.js
> +
use reject

2022-08-03 19:14 UTC, merged