Feature/auth with google id token
cboard-org/cboard-api pull request #341
Opened 2023-12-12 23:58 UTC by tomivm

Allow Login with Firebase on Android and IOS

2023-12-13 20:16 UTC, RodriSanchez1 requested changes

2023-12-13 20:16 UTC, RodriSanchez1 commented on api/controllers/user.js
> +        console.error(err);
The parameter on `console.error` its wrong. Its `err` instead `error`

2023-12-13 20:16 UTC, RodriSanchez1 commented on api/controllers/user.js
> +        res.redirect('/');
Why do you use a redirect here? I think we can directly use  `res.status(404).json({message: "Something went wrong on Google Id Token login"});`

2023-12-13 20:16 UTC, RodriSanchez1 commented on api/controllers/user.js
> +    res.redirect('/');
Same than above

2023-12-13 21:10 UTC, RodriSanchez1 commented on api/controllers/user.js
> +      audience: [process.env.GOOGLE_FIREBASE_SIGN_IN_APP_ID, process.env.GOOGLE_FIREBASE_WEB_CLIENT_SIGN_IN]
change `process.env.GOOGLE_FIREBASE_WEB_CLIENT_SIGN_IN` to `process.env.GOOGLE_FIREBASE_WEB_CLIENT_ID` please :)

2023-12-14 18:42 UTC, martinbedouret approved these changes

2023-12-14 18:42 UTC, merged